// 수집 대상 RSS 소스 목록 — seed-sources.mjs, fetch-feeds.mjs 공용
export const sources = [
  {
    slug: "hankyung",
    name: "한국경제",
    category: "domestic",
    language: "ko",
    feedUrl: "https://www.hankyung.com/feed/economy",
    siteUrl: "https://www.hankyung.com",
  },
  {
    slug: "mk",
    name: "매일경제",
    category: "domestic",
    language: "ko",
    feedUrl: "https://www.mk.co.kr/rss/30100041/",
    siteUrl: "https://www.mk.co.kr",
  },
  {
    slug: "press-releases",
    name: "Press Releases",
    category: "international",
    language: "en",
    feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
    siteUrl: "https://www.federalreserve.gov/newsevents/pressreleases.htm",
  },
  {
    slug: "monetary-policy",
    name: "Monetary Policy",
    category: "international",
    language: "en",
    feedUrl: "https://www.federalreserve.gov/feeds/press_monetary.xml",
    siteUrl: "https://www.federalreserve.gov/monetarypolicy.htm",
  },
  {
    slug: "speeches-testimony",
    name: "Speeches and Testimony",
    category: "international",
    language: "en",
    feedUrl: "https://www.federalreserve.gov/feeds/speeches_and_testimony.xml",
    siteUrl: "https://www.federalreserve.gov/newsevents/speeches.htm",
  },
  {
    slug: "feds-notes",
    name: "FEDS Notes",
    category: "international",
    language: "en",
    feedUrl: "https://www.federalreserve.gov/feeds/feds_notes.xml",
    siteUrl: "https://www.federalreserve.gov/econres/notes/feds-notes/",
  },
  {
    slug: "interest-rates",
    name: "Selected Interest Rates",
    category: "international",
    language: "en",
    feedUrl: "https://www.federalreserve.gov/feeds/h15.xml",
    siteUrl: "https://www.federalreserve.gov/releases/h15/",
  },
  {
    slug: "fx-rates",
    name: "Foreign Exchange Rates",
    category: "international",
    language: "en",
    feedUrl: "https://www.federalreserve.gov/feeds/h10.xml",
    siteUrl: "https://www.federalreserve.gov/releases/h10/",
  },
];
